
language: node_js
node_js:
  - "0.10"
services:
  - mongodb
env:
  global:
    - NODE_ENV=travisci
    - BUILD_DIR=`pwd`/accraze
before_script:
  - npm install
  - mongo localhost:27017/latestCraze seed.js